# runtime image including CA certs and tzdata
FROM gcr.io/distroless/static-debian12:latest
# Copy our static executable.
COPY go-find-liquor /go/bin/go-find-liquor
# Expose port for publishing as web service
# EXPOSE 8081
# Run the binary.
ENTRYPOINT ["/go/bin/go-find-liquor"]
