---
services:
  go-find-liquor:
    container_name: go-find-liquor
    image: toozej/go-find-liquor:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - "./config.yaml:/config.yaml:ro"
    read_only: true
    labels:
      - "traefik.enable=false"
