---
version: "3"
services:
  go-find-liquor:
    container_name: go-find-liquor
    image: toozej/go-find-liquor:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    labels:
      - "traefik.enable=false"
      # labels below for publishing as web service
      # - "traefik.docker.network=traefik"
      # - "traefik.http.routers.go-find-liquor.rule=Host(`go-find-liquor.test`)"
      # - "traefik.http.routers.go-find-liquor.middlewares=http-redirect-https@file,headers@file"
      # - "traefik.http.routers.go-find-liquor-secure.entrypoints=https"
      # - "traefik.http.routers.go-find-liquor-secure.rule=Host(`go-find-liquor.test`)"
      # - "traefik.http.routers.go-find-liquor-secure.middlewares=headers@file"
      # - "traefik.http.routers.go-find-liquor-secure.tls=true"
    # networks:
      # - traefik
